/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as GSlugIndexRouteImport } from './routes/g.$slug.index'
import { Route as GSlugExpensesRouteImport } from './routes/g.$slug.expenses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugIndexRoute = GSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GSlugRoute,
} as any)
const GSlugExpensesRoute = GSlugExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => GSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/g/$slug/expenses': typeof GSlugExpensesRoute
  '/g/$slug/': typeof GSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/g/$slug/expenses': typeof GSlugExpensesRoute
  '/g/$slug': typeof GSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/g/$slug/expenses': typeof GSlugExpensesRoute
  '/g/$slug/': typeof GSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/g/$slug' | '/g/$slug/expenses' | '/g/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/g/$slug/expenses' | '/g/$slug'
  id: '__root__' | '/' | '/g/$slug' | '/g/$slug/expenses' | '/g/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GSlugRoute: typeof GSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/': {
      id: '/g/$slug/'
      path: '/'
      fullPath: '/g/$slug/'
      preLoaderRoute: typeof GSlugIndexRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/g/$slug/expenses': {
      id: '/g/$slug/expenses'
      path: '/expenses'
      fullPath: '/g/$slug/expenses'
      preLoaderRoute: typeof GSlugExpensesRouteImport
      parentRoute: typeof GSlugRoute
    }
  }
}

interface GSlugRouteChildren {
  GSlugExpensesRoute: typeof GSlugExpensesRoute
  GSlugIndexRoute: typeof GSlugIndexRoute
}

const GSlugRouteChildren: GSlugRouteChildren = {
  GSlugExpensesRoute: GSlugExpensesRoute,
  GSlugIndexRoute: GSlugIndexRoute,
}

const GSlugRouteWithChildren = GSlugRoute._addFileChildren(GSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GSlugRoute: GSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
